theme:
  name: material
  features:
    - navigation.tabs
site_name:
  ENG1 2022/23 Group 2

nav:
  - index.md
  - downloads.md
  - one/assessment_one.md
      - one/initial_planning.md
      - one/weekly_updates.md
  - two/assessment_two.md
      - two/initial_planning.md
      - two/weekly_updates.md
