theme:
  name: material
  features:
    - navigation.tabs
site_name:
  ENG1 2022/23 Group 2

nav:
  - Home:
      - index.md
  - Downloads:
      - downloads.md
  - Assessment One
      - one/assessment_one.md
      - Initial Planning: one/initial_planning.md
      - Weekly Updates: one/weekly_updates.md
  - Assessment Two
      - assessment_two.md
      - Initial Planning: two/initial_planning.md
      - Weekly Updates: two/weekly_updates.md
