theme:
  name: material
  features:
    - navigation.tabs
site_name:
  ENG1 2022/23 Group 2

nav:
  - Home: "index.md"
  - Downloads: "downloads.md"
  - Assessment One:
      - Planning: "one/initial_planning.md"
      - Weekly Updates: "one/weekly_updates.md"
  - Assessment Two:
      - Planning: "two/initial_planning.md"
      - Weekly Updates: "two/weekly_updates.md"
